chore: try fix sql review

diff --git a/.github/workflows/sql-review.yml b/.github/workflows/sql-review.yml
--- a/.github/workflows/sql-review.yml
+++ b/.github/workflows/sql-review.yml
@@ -28,15 +28,15 @@ jobs:
             '$ARGS.named')
 
           response=$(curl -s -w "%{http_code}" -X POST ${bytebase_api}/sql/check \
-            -H "Authorization: Bearer '${bytebase_token}'" \
-            -d "$request_body")
-          echo "::debug::response $response"
+            -H "Authorization: Bearer ${bytebase_token}" \
+            -d "${request_body}")
+          echo "::debug::response ${response}"
 
-          http_code=$(tail -n1 <<< "$response")
-          body=$(sed '$ d' <<< "$response")
+          http_code=$(tail -n1 <<< "${response}")
+          body=$(sed '$ d' <<< "${response}")
 
-          if [ $http_code != 200 ]; then
-            echo ":error::Failed to check SQL with response code $http_code and body $body"
+          if [ ${http_code} != 200 ]; then
+            echo ":error::Failed to check SQL with response code ${http_code} and body $body"
             exit 1
           fi
 
@@ -45,6 +45,6 @@ jobs:
 
           while read message; do
             echo $message
-          done <<< "$(echo $content | jq -r '.[]')"
+          done <<< "$(echo ${content} | jq -r '.[]')"
 
-          if [ "$status" == "ERROR" ]; then exit 1; fi
+          if [ "${status}" == "ERROR" ]; then exit 1; fi
